codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...90"
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
